version: '3'

services:
  roundcube:
    container_name: imapsync_roundcube
    image: roundcube/roundcubemail:latest
    networks:
      - imapsyncnet
    volumes:
      - ./roundcube/db:/var/roundcube/db
      - ./roundcube/config:/var/roundcube/config
    ports:
      - 8090:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://imapsync_dovecot
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://imap.gmail.com
    restart: unless-stopped
  dovecot:
    container_name: imapsync_dovecot
    image: dovecot/dovecot:latest
    volumes:
      - ./dovecot/data:/srv/mail
    ports:
      - 143:143
    restart: unless-stopped
    networks:
      - imapsyncnet

networks:
  imapsyncnet: ~
